### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by H4xl0r**
Added The mysterious Landing Page Browser Stats Script :-)

needs to be added to all !

### CODE REVIEW

**Comment by kbeflo** [comment]
@H4xl0r I'll check it out as soon as I can, I've been working on updating the portals recently.

**Comment by kbeflo** [comment]
I'm getting multiple user agents from connecting once on a captive portal login. 

Using LineageOS 16 Android System WebView 79... (Chromium)

image

**Comment by H4xl0r** [comment]
sure the function / regex is way old and not working 
`
function identifyUserAgent($userAgent)
{
    if (preg_match('/^Mozilla/', $userAgent)) {
        if (preg_match('/Chrome\/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/', $userAgent)) {
            increment_browser('chrome');
        } elseif (preg_match('/Safari\/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/', $userAgent)) {
            increment_browser('safari');
        } elseif (strpos($userAgent, 'MSIE ') || preg_match('/Trident\/[0-9]/', $userAgent)) {
            increment_browser('internet_explorer');
        } elseif (preg_match('/Firefox\/[0-9]{1,3}\.[0-9]{1,3}/', $userAgent)) {
            increment_browser('firefox');
        } else {
            increment_browser('other');
        }
    } elseif (preg_match('/^Opera\/[0-9]{1,3}\.[0-9]/', $userAgent)) {
        increment_browser('opera');
    } else {
        increment_browser('other');
    }
}
`

We would need to fix those useragents or update 
as mentioned its the old ancient pinapple function
but it should be done easy , just change the regex
I dont had the time jet but here are some exapmles to do so 👍 
https://github.com/GabrielDelepine/browser-regex-detector/blob/main/script.php
https://jonlabelle.com/snippets/view/yaml/browser-user-agent-regular-expressions

**Comment by H4xl0r** [comment]
got a new one 
@kbeflo 
just have a look on my git and tell me if i should pull

**Pull request closed without merging**
